### ISSUE TITLE
Update Cluster-Proxy-Addon doc

### ISSUE THREAD

**Issue by xuezhaojun** [stolostron/codesweep#1]
### Task Description

in pkg/serviceproxy/readme.md there is a error:

originaly, I use:

```
SA_TOKEN=$(oc create token test-sa -n test)
```

But this command only works for kubernetes 1.24+，for 1.23 and lower, we need to:

```
oc apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: test-sa
  namespace: test
  annotations:
    kubernetes.io/service-account.name: test-sa
type: kubernetes.io/service-account-token
EOF

SA_TOKEN=$(oc get secret test-sa -n test -o jsonpath='{.data.token}' | base64 -d)
```

Please help me update the doc to contain both situation.

### Target Repositories

- [ ] open-cluster-management-io/ocm
- [ ] open-cluster-management-io/managed-serviceaccount
- [ ] open-cluster-management-io/cluster-proxy
- [ ] stolostron/ocm
- [ ] stolostron/managed-serviceaccount
- [ ] stolostron/cluster-proxy
- [ ] stolostron/managedcluster-import-controller
- [ ] stolostron/multicloud-operators-foundation
- [x] stolostron/cluster-proxy-addon
- [ ] stolostron/clusterlifecycle-state-metrics
- [ ] stolostron/klusterlet-addon-controller
- [ ] stolostron/cluster-lifecycle-api
- [ ] stolostron/backplane-operator
